update name

diff --git a/.github/workflows/playwright-pr.yml b/.github/workflows/playwright-pr.yml
--- a/.github/workflows/playwright-pr.yml
+++ b/.github/workflows/playwright-pr.yml
@@ -53,20 +53,27 @@ jobs:
         fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
         EOF
 
-    - name: Upload Playwright report (PR)
-      if: ${{ !cancelled() && github.event_name == 'pull_request' }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: playwright-report-${{ github.run_id }}
-        path: playwright-report/
+    # - name: Upload Playwright report (PR)
+    #   if: ${{ !cancelled() && github.event_name == 'pull_request' }}
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: playwright-report-${{ github.run_id }}
+    #     path: playwright-report/
 
-    - name: Debug report folder
+    # - name: Debug report folder
+    #   if: always()
+    #   run: |
+    #     echo "PWD:"
+    #     pwd
+    #     echo "FILES:"
+    #     ls -la
+    #     echo "REPORT:"
+    #     ls -la playwright-report/index.html || echo "❌ playwright-report NOT found"
+  
+    - name: Add summary
       if: always()
       run: |
-        echo "PWD:"
-        pwd
-        echo "FILES:"
-        ls -la
-        echo "REPORT:"
-        ls -la playwright-report/index.html || echo "❌ playwright-report NOT found"
+        echo "## 📊 Playwright Tests" >> $GITHUB_STEP_SUMMARY
+        echo "✔ Tests executed" >> $GITHUB_STEP_SUMMARY
+        echo "📄 Report: https://rosygit-creator.github.io/Playwright_TS/" >> $GITHUB_STEP_SUMMARY
        
